### ISSUE TITLE
End-of-day summary email notification

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/iobox-win32#21]
Add a feature that automatically send a summary email notification at the end of day summarizing: 
- number of success files
- number of duplicates
- number of fail cases and reasons if possible

**Comment by svoinea** [comment]
Implemented in commit 1deef29702acd7665eb5725364e6fbca889a4c70

**Comment by svoinea** [comment]
Ready for review.

**Comment by akumar03** [comment]
Not working on windows 7 installation. Here is error log:
016-07-14 18:28:12,552: DEBUG <client>: Sending request: method="GET", url="https://dev.gpcrconsortium.org/ermrest/catalog/1/attributegroup/iobox_mgmt:report/Notified=f/Action;Requests:=cnt(Action)", headers="{'Cookie': 'ermrest=7ejPzhfSjq2aRl1C65gtceS5', 'Content-Type': 'application/json'}"
2016-07-14 18:28:12,749: DEBUG <client>: Response: 409
2016-07-14 18:28:12,749: ERROR <client>: Error response: method="GET", url="https://dev.gpcrconsortium.org/ermrest/catalog/1/attributegroup/iobox_mgmt:report/Notified=f/Action;Requests:=cnt(Action)", status=409, error: 409 Conflict
The request conflicts with the state of the server. Table report does not exist in schema iobox_mgmt.

2016-07-14 18:28:12,749: DEBUG <observer>: Error generated during the report summary "/ermrest/catalog/1/attributegroup/iobox_mgmt:report/Notified=f/Action;Requests:=cnt(Action)":
Error response (409) received: 409 Conflict
The request conflicts with the state of the server. Table report does not exist in schema iobox_mgmt.
.
2016-07-14 18:28:12,749: ERROR <serviceconfig>: got exception "No module named text"
2016-07-14 18:28:12,749: ERROR <serviceconfig>: ['Traceback (most recent call last):\n', '  File "serviceconfig.pyc", line 158, in sendMail\n', '  File "email\**init**.pyc", line 79, in **getattr**\n', 'ImportError: No module named text\n']

**Comment by svoinea** [comment]
@akumar03 : Problem might be fixed now through the commit 8d4161c405a1a87ed9274cdda0f92f17ec98e7d2.

I have changed the Python packages from where to extract the email modules.
